name: AirPrint Server
version: "1.7"
slug: cupsik
boot: auto
startup: system
description: A CUPS print server with working AirPrint
arch:
  - amd64
  - aarch64
usb: true
init: false
panel_icon: mdi:printer
hassio_role: default
hassio_api: true
homeassistant_api: true

ports:
  631/tcp: 631
  631/udp: 631
  5353/udp: 5353
map:
  - type: ssl
    read_only: true
    path: /ssl
  - type: addon_config
    read_only: false
    path: /config
ingress: true
ingress_port: 631
# ingress_stream: true
full_access: true
watchdog: http://[HOST]:[PORT:631]/printers
schema:
  log_level: list(debug2|debug|info|notice|warn|error|crit|alert|none)?
  packages:
    - str?
