name: AirPrint Server
version: "1.7"
slug: cupsik
boot: auto
startup: system
description: A CUPS print server with working AirPrint
arch:
  - amd64
  - aarch64
usb: true
init: false
panel_icon: mdi:printer
hassio_role: default
hassio_api: true
homeassistant_api: true
host_network: true
host_dbus: true
# apparmor: false
ports:
  631/tcp: 631
  631/udp: 631
map:
  - type: ssl
    read_only: true
    path: /ssl
  - type: addon_config
    read_only: false
    path: /config

ingress: true
ingress_port: 631
privileged: true
# ingress_stream: true

watchdog: http://[HOST]:[PORT:631]/printers
options:
  use_host_dbus: false
schema:
  log_level: list(debug2|debug|info|notice|warn|error|crit|alert|none)?
  packages:
    - str?
  use_host_dbus: bool?
